hao-ai-lab/FastVideo

README.md, fastvideo/distill.py, fastvideo/distill_adv.py, fastvideo/train.py, fastvideo/utils/checkpoint.py, fastvideo/utils/load.py, fastvideo/utils/validation.py, scripts/distill/distill_hunyuan.sh, scripts/finetune/finetune_hunyuan.sh
=> [Fix] Save CK, Dataset bug fix 

.github/workflows/fastvideo-publish.yml, .github/workflows/sta-publish.yml, .github/workflows/test.yml, csrc/sliding_tile_attention/MANIFEST.in, csrc/sliding_tile_attention/setup.py, pyproject.toml
This PR introduces automatic PyPI publishing for FastVideo and Sliding Tile Attention through GitHub Actions workflows. The workflows are triggered when version numbers are changed in their respective configuration files.
- **Version-Based Triggers**: Packages are only published when their version numbers are intentionally updated
- **Automated Build Process**: Handles all build steps automatically without manual intervention
- **Secure Deployment**: Uses PyPI's OIDC Trusted Publishing method for secure authentication
- **Compatibility Support**: 
- Supports multiple Python versions (3.10-3.13)
- Compatible with various PyTorch and CUDA versions
- Generates appropriately named packages with compatibility indicators
- Streamlines release process by eliminating manual publishing steps
- …
=> Establish cicd workflow to build and publish FastVideo and STA Kernel

.github/scripts/runpod_api.py, .github/scripts/runpod_cleanup.py, .github/workflows/pr-test.yml
To avoid triggering all workflows and jobs for all PRs, this change adds filters for triggering the pr-test workflow, as well as job level filters for running the encoder test job only if the v1/models/encoder/ or v1/models/loader/ files are changed.
- Workflow will trigger if the workflow file itself changes
\
\
Additionally, a new job `runpod-cleanup` is added as a failsafe in the event that any test jobs are unable to terminate their RunPod instances, and pods become stranded. This may happen due to the new timeout for the encoder test, which was added to prevent indefinitely running tests or hanging Github runners.
- This job will not touch any pods other than the ones started in the same workflow--pods are identified by their {JOB ID}-{WORKFLOW ID}
- This job only runs after all …
=> [CI] Add test workflow improvements

.github/scripts/runpod_api.py
It seems not all RunPod GPUs support CUDA 12.4, and you have to specify which versions you allow when creating an instance to guarantee support.
Also disables output buffering on subprocess for more frequent logging.
=> [CI] Set allowedCudaVersions

.github/scripts/runpod_api.py, .github/workflows/build-image.yml, .github/workflows/pr-test.yml, Dockerfile
Adds manual workflow for building and pushing images to the GitHub Container Registry. PR test jobs will now have RunPod pull these images to create containers. Uncached, this takes around 6-7 minutes. Apparently, RunPod supports local layer caching in all its data centers, so hopefully subsequent pods using the same image in the same region/machine will be able to start up much faster.
=> [CI] Support custom Docker image

fastvideo/v1/entrypoints/cli/cli_types.py, fastvideo/v1/entrypoints/cli/generate.py
Fixes issue where using the cli outputs  `argparse.ArgumentError: argument --num-gpus: conflicting option string: --num-gpus`, due to the argument being added to FastVideoArgs.
Also fixes issue where super().__init__() overwrites the GenerateSubcommand name, preventing proper validation.
=> [CLI] Fix duplicate --num-gpus

.pre-commit-config.yaml, fastvideo/v1/attention/layer.py, fastvideo/v1/attention/selector.py, fastvideo/v1/configs/__init__.py, fastvideo/v1/configs/hunyuan.py, fastvideo/v1/configs/registry.py, fastvideo/v1/configs/wan.py, fastvideo/v1/distributed/__init__.py, fastvideo/v1/entrypoints/video_generator.py, fastvideo/v1/fastvideo_args.py, fastvideo/v1/models/dits/base.py, fastvideo/v1/models/dits/hunyuanvideo.py, fastvideo/v1/models/dits/wanvideo.py, fastvideo/v1/models/encoders/base.py, fastvideo/v1/models/encoders/clip.py, fastvideo/v1/models/encoders/llama.py, fastvideo/v1/models/vaes/wanvae.py, fastvideo/v1/pipelines/stages/clip_image_encoding.py, fastvideo/v1/pipelines/stages/clip_text_encoding.py, fastvideo/v1/pipelines/stages/denoising.py, fastvideo/v1/pipelines/stages/llama_encoding.py, fastvideo/v1/pipelines/stages/t5_encoding.py, fastvideo/v1/pipelines/wan/wan_i2v_pipeline.py, fastvideo/v1/utils.py, fastvideo/v1/worker/executor.py, fastvideo/v1/worker/gpu_worker.py, fastvideo/v1/worker/multiproc_executor.py
Changes:
- Adds process name and pid prefix to worker logging
- change supported_attn_backends's type from List to Tuple to support caching get_attn_backend(); eliminates spam logging msg from cuda.py
=> [V1] Worker cleanup; Logging clean up; enables isort again

README.md, docs/source/getting_started/installation.md, pyproject.toml
Tested that FastVideo also works on Python 3.11 and 3.12
=> chore: Release FastVideo 0.0.2 and update python requirements

fastvideo/v1/entrypoints/video_generator.py, fastvideo/v1/worker/gpu_worker.py, fastvideo/v1/worker/multiproc_executor.py
Issues found while attempting to use the new API in ComfyUI.
GPU worker change ensures CPU memory has access to forward output--fixes `RuntimeError: cudaMallocAsync does not yet support shareIpcHandle`
Removal of signal handlers do not seem to affect current gradio and basic examples, while avoiding `signal only works in main thread of the main interpreter` and the need to propagate signals from worker -> main thread
=> [V1] Worker improvements/cleanup

fastvideo/v1/entrypoints/video_generator.py, fastvideo/v1/worker/executor.py, fastvideo/v1/worker/gpu_worker.py, fastvideo/v1/worker/multiproc_executor.py
These changes allow for the early termination and graceful interruption of generations. This is particularly useful when using jupyter notebook where the `VideoGenerator` is kept in memory and the `generate_video()` call can be freely interrupted and restarted with a new batch
=> [misc] Improve worker cleanup

examples/inference/optimizations/README.md, examples/inference/optimizations/attention_example.py, examples/inference/optimizations/teacache_example.py, fastvideo/distill.py, fastvideo/distill_adv.py, fastvideo/models/hunyuan/inference.py, fastvideo/train.py, fastvideo/v1/distributed/utils.py, fastvideo/v1/entrypoints/video_generator.py, fastvideo/v1/inference_engine.py, fastvideo/v1/pipelines/stages/base.py, fastvideo/v1/worker/multiproc_executor.py, predict.py, scripts/dataset_preparation/resize_videos.py
For this purpose, `time.time()` should not be used to measure inference code speed, as well as benchmarks, instead we should use `time.perf_counter()`. See: https://peps.python.org/pep-0418/#rationale 👍
=> [Misc] Replace instances of `time.time()` with `time.perf_counter()`

fastvideo/v1/models/dits/base.py, fastvideo/v1/models/dits/hunyuanvideo.py, fastvideo/v1/models/dits/wanvideo.py
More sensible behavior in DiTs when forward_context's batch is None -- especially needed when using DiT for training/distill
=> [Teacache] allow None for forward_context batch when using teacache

fastvideo/v1/worker/gpu_worker.py
The multiproc_executor pipe was getting stuck in a faulty state, which can be seen if inference is attempted again after an interrupt, as it's expecting a response from the workers.
=> Fulfill worker response on interrupt

csrc/sliding_tile_attention/test/test_sta.py, fastvideo/models/hunyuan/idle_config.py, fastvideo/models/hunyuan/inference.py, fastvideo/models/hunyuan/prompt_rewrite.py, fastvideo/models/stepvideo/text_encoder/stepllm.py
Remove deprecated https://docs.pytorch.org/docs/stable/generated/torch.norm.html as well as `torch.cuda.amp.autocast` which is also deprecated
And minor docstrings/CLI args.
=> [Misc] Small fixes to Torch code

fastvideo/v1/attention/layer.py, fastvideo/v1/attention/selector.py, fastvideo/v1/configs/models/dits/base.py, fastvideo/v1/configs/models/encoders/base.py, fastvideo/v1/models/dits/base.py, fastvideo/v1/models/dits/hunyuanvideo.py, fastvideo/v1/models/dits/stepvideo.py, fastvideo/v1/models/dits/wanvideo.py, fastvideo/v1/models/encoders/base.py, fastvideo/v1/pipelines/stages/denoising.py, fastvideo/v1/platforms/__init__.py, fastvideo/v1/platforms/cuda.py, fastvideo/v1/platforms/interface.py
https://github.com/hao-ai-lab/FastVideo/pull/513 leaves a bug that the `envs.FASTVIDEO_ATTENTION_BACKEND` could still be VSA even when VSA is not available and the backend selects something else.
This PR fixes it.
=> [Refactor] Fix attn backend selection not correctly setting env variable

.github/workflows/pr-test.yml
Now draft PRs won't trigger anything, and correctly restrict precision tests to the paths
=> [CI] Fix CI checks

fastvideo/v1/layers/layernorm.py
Hi from pytorch distributed, thanks for asking questions for fully_shard https://github.com/pytorch/pytorch/issues/157209
want to help how fully_shard should be applied if we decide to hack forward_native, or even better, use avoid hacking forward_native
=> fully_shard usage on RMSNorm

fastvideo/v1/configs/pipelines/base.py, fastvideo/v1/configs/pipelines/wan.py, fastvideo/v1/configs/wan_1.3B_t2v_pipeline.json, fastvideo/v1/configs/wan_14B_i2v_480p_pipeline.json
Wan precisions from https://github.com/hao-ai-lab/FastVideo/pull/358 were incorrect. Note that even after this PR, if you run the following script, the `prompt_embed` from text encoder is still mismatching huggingface, making it harder to write lora tests.
https://huggingface.co/Wan-AI/Wan2.1-T2V-1.3B-Diffusers
```
import torch
from diffusers import AutoencoderKLWan, WanPipeline
from diffusers.schedulers.scheduling_unipc_multistep import (
UniPCMultistepScheduler)
from diffusers.utils import export_to_video
model_id = "Wan-AI/Wan2.1-T2V-1.3B-Diffusers"
vae = AutoencoderKLWan.from_pretrained(model_id,
subfolder="vae",
torch_dtype=torch.float32)
pipe = WanPipeline.from_pretrained(model_id,
vae=vae,
torch_dtype=torch.bfloat16)
pipe.scheduler = …
```
=> Fix VAE precisions

fastvideo/v1/distributed/parallel_state.py, fastvideo/v1/entrypoints/video_generator.py, fastvideo/v1/models/vaes/common.py, fastvideo/v1/pipelines/stages/encoding.py, fastvideo/v1/pipelines/stages/image_encoding.py, fastvideo/v1/training/training_pipeline.py, fastvideo/v1/worker/gpu_worker.py
`empty_cache` is super expensive because it scans all the blocks in torch's cache allocator to defragment small blocks. (See https://discuss.pytorch.org/t/gpu-ram-fragmentation-diagnostics/34073/6) When the allocation pattern is stable with no memory leaks, it's not helpful and slows things down a lot.
The better approach is to write code without memory leaks and use offload/reduce seqlen.
=> Remove all unnecessary torch.cuda.empty_cache

fastvideo/attention/layer.py, fastvideo/fastvideo_args.py, fastvideo/models/loader/component_loader.py, fastvideo/pipelines/composed_pipeline_base.py, fastvideo/platforms/__init__.py
`python examples/inference/basic/basic.py`
=> [Feature] Optionally enable torch compile 

csrc/attn/benchmarks/bench_sta.py, examples/distill/Wan2.1-T2V/Wan-Syn-Data-480P/distill_dmd_VSA_t2v_1.3B.slurm, examples/distill/Wan2.1-T2V/Wan-Syn-Data-480P/distill_dmd_VSA_t2v_14B.slurm, examples/distill/Wan2.1-T2V/Wan-Syn-Data-480P/distill_dmd_t2v_1.3B.slurm, examples/distill/Wan2.2-TI2V-5B-Diffusers/Data-free/distill_dmd_t2v_5B.sh, examples/distill/Wan2.2-TI2V-5B-Diffusers/Data-free/distill_dmd_t2v_5B_VSA.sh, examples/distill/Wan2.2-TI2V-5B-Diffusers/crush_smol/distill_dmd_VSA_t2v_5B.sh, examples/inference/lora/wan_lora_inference_from_ckpt.py, examples/training/finetune/Wan2.1-Fun-1.3B-InP/crush_smol/finetune_i2v.sh, examples/training/finetune/Wan2.1-Fun-1.3B-InP/crush_smol/finetune_i2v.slurm, examples/training/finetune/wan_i2v_14B_480p/crush_smol/finetune_i2v.sh, examples/training/finetune/wan_i2v_14B_480p/crush_smol/finetune_i2v.slurm, examples/training/finetune/wan_i2v_14B_480p/crush_smol/finetune_i2v_lora.sh, examples/training/finetune/wan_t2v_1.3B/crush_smol/finetune_t2v.sh, examples/training/finetune/wan_t2v_1.3B/crush_smol/finetune_t2v.slurm, examples/training/finetune/wan_t2v_1.3B/crush_smol/finetune_t2v_lora.sh, fastvideo/pipelines/stages/decoding.py, fastvideo/pipelines/stages/denoising.py, fastvideo/training/distillation_pipeline.py, fastvideo/training/training_pipeline.py, fastvideo/worker/gpu_worker.py, scripts/distill/v1_distill_dmd_wan.sh, scripts/distill/v1_distill_dmd_wan_VSA.sh, scripts/finetune/finetune_v1.sh
torch will automatically call this when it runs out of memory, and manually calling will only slow program down.
See  https://discuss.pytorch.org/t/about-torch-cuda-empty-cache/34232/9
=> Remove all empty_cache
