hao-ai-lab/FastVideo

fastvideo/distill.py

https://github.com/hao-ai-lab/FastVideo/issues/217

update cfg bug?

---

fastvideo/v1/layers/activation.py
fastvideo/v1/layers/custom_op.py
fastvideo/v1/layers/layernorm.py
fastvideo/v1/layers/rotary_embedding.py
fastvideo/v1/models/encoders/llama.py
fastvideo/v1/models/loader/fsdp_load.py
fastvideo/v1/models/parameter.py
fastvideo/v1/platforms/__init__.py
fastvideo/v1/tests/test_llama_encoder.py
fastvideo/v1/third_party/pynvml.py
fastvideo/v1/utils.py

Various cleanups and removes the annoying spam of "Current VLLM config is not set." when running v1

[v1] cleanup and remove more vllm dependencies

---

fastvideo/v1/layers/activation.py
fastvideo/v1/layers/custom_op.py
fastvideo/v1/layers/layernorm.py
fastvideo/v1/layers/linear.py
fastvideo/v1/layers/mlp.py
fastvideo/v1/layers/rotary_embedding.py
fastvideo/v1/layers/utils.py
fastvideo/v1/layers/visual_embedding.py
fastvideo/v1/layers/vocab_parallel_embedding.py
format.sh
pyproject.toml

done with type checking - v1/layers/

---

.github/workflows/docs.yml
docs/source/developer_guide/overview.md
docs/source/index.md
pyproject.toml

[Docs] Add dev guide and doc building CI

---

.github/workflows/docs.yml
docs/source/generate_examples.py
docs/source/index.md
fastvideo/v1/distributed/__init__.py
fastvideo/v1/examples/inference/basic/README.md
fastvideo/v1/examples/inference/basic/basic.py
fastvideo/v1/examples/inference/gradio/README.md
fastvideo/v1/examples/inference/gradio/gradio_demo.py
fastvideo/v1/logger.py
fastvideo/v1/pipelines/stages/denoising.py
fastvideo/v1/worker/gpu_worker.py
fastvideo/v1/worker/multiproc_executor.py

Refactor of the old gradio demo to support v1. Showcases a basic implementation of what can be done with the new user API.
Change to multiproc_executor is to allow sigints to propogate to the main process and not be trapped by the workers, which in this case allows the gradio server to shut down properly.

[V1] Gradio demo with new API

---

fastvideo/v1/attention/backends/sage_attn.py
fastvideo/v1/envs.py
fastvideo/v1/models/dits/hunyuanvideo.py
fastvideo/v1/models/dits/wanvideo.py
fastvideo/v1/platforms/cuda.py
fastvideo/v1/platforms/interface.py

Use `export FASTVIDEO_ATTENTION_BACKEND=SAGE_ATTN` to use

[Attn] Add SageAttention Backend

---

fastvideo/v1/configs/pipelines/base.py
fastvideo/v1/examples/inference/basic/basic.py
fastvideo/v1/fastvideo_args.py
fastvideo/v1/models/loader/component_loader.py
fastvideo/v1/pipelines/stages/decoding.py
fastvideo/v1/pipelines/stages/input_validation.py
fastvideo/v1/tests/encoders/test_clip_encoder.py
fastvideo/v1/tests/encoders/test_llama_encoder.py
fastvideo/v1/tests/encoders/test_t5_encoder.py
fastvideo/v1/worker/gpu_worker.py

Small Fixes & Features

---

fastvideo/v1/configs/models/dits/base.py
fastvideo/v1/configs/models/dits/hunyuanvideo.py
fastvideo/v1/configs/models/dits/wanvideo.py
fastvideo/v1/configs/pipelines/__init__.py
fastvideo/v1/configs/pipelines/registry.py
fastvideo/v1/configs/pipelines/wan.py
fastvideo/v1/configs/sample/base.py
fastvideo/v1/configs/sample/registry.py
fastvideo/v1/configs/sample/wan.py
fastvideo/v1/models/dits/base.py
fastvideo/v1/models/dits/hunyuanvideo.py
fastvideo/v1/models/dits/wanvideo.py
fastvideo/v1/models/loader/component_loader.py
fastvideo/v1/pipelines/pipeline_batch_info.py
fastvideo/v1/pipelines/stages/input_validation.py

[Misc] Small Fixes & Features

---

.pre-commit-config.yaml
docs/source/getting_started/installation.md
docs/source/getting_started/v1_api.md
docs/source/index.md
docs/source/inference/add_pipeline.md
docs/source/inference/inference_quick_start.md
docs/source/inference/optimizations.md
docs/source/inference/support_matrix.md
examples/inference/basic/README.md
examples/inference/gradio/README.md
examples/inference/optimizations/README.md
fastvideo/__init__.py

- Added `uv` to installation instructions
- Reformatted compatibility matrix
- moved adding_pipeline to inference

[Docs] More docs update

---

fastvideo/__init__.py

Added version in __init__.py. Previously users couldn't see version 
cc @SolitaryThinker

Fix version number 

---

.github/workflows/pr-test.yml

Pre-requisite of https://github.com/hao-ai-lab/FastVideo/pull/432

misc: Trigger transformers CI for layers and attention code change

---

fastvideo/v1/distributed/__init__.py
fastvideo/v1/distributed/device_communicators/base_device_communicator.py
fastvideo/v1/distributed/device_communicators/cuda_communicator.py
fastvideo/v1/distributed/parallel_state.py

also adds op argument to all_reduce

[Training] [2/n] add bwd for all2all and all_gather

---

fastvideo/v1/models/dits/base.py
fastvideo/v1/models/dits/hunyuanvideo.py
fastvideo/v1/models/dits/stepvideo.py
fastvideo/v1/models/dits/wanvideo.py
fastvideo/v1/models/loader/component_loader.py
fastvideo/v1/pipelines/training_utils.py

Have DiTs keep a copy of the HF config around to be written to disk during weight checkpoints

[Training] [4/n] add training save checkpoint

---

fastvideo/dataset/transform.py
fastvideo/v1/dataset/__init__.py
fastvideo/v1/dataset/dataloader/schema.py
fastvideo/v1/dataset/latent_datasets.py
fastvideo/v1/dataset/parquet_datasets.py
fastvideo/v1/dataset/t2v_datasets.py
fastvideo/v1/dataset/transform.py
fastvideo/v1/dataset/upload_to_hf.py

[Training] [1/n] Add latent datasets

---

fastvideo/v1/utils.py
pyproject.toml

Use it like this
`python fastvideo/v1/tests/vaes/test_hunyuan_vae.py`
`telnet 127.0.0.1 45833`

misc: add remote pdb for debugging workers

---

fastvideo/distill.py
fastvideo/distill_adv.py
fastvideo/sample/sample_t2v_hunyuan_hf.py
fastvideo/sample/sample_t2v_mochi.py
fastvideo/train.py
fastvideo/utils/checkpoint.py
fastvideo/v1/dataset/latent_datasets.py
fastvideo/v1/distributed/parallel_state.py
fastvideo/v1/pipelines/composed_pipeline_base.py
fastvideo/v1/training/__init__.py
fastvideo/v1/training/training_pipeline.py
fastvideo/v1/training/wan_training_pipeline.py
pyproject.toml

Summarizes my comments on the previously merged PRs. 
cc @BrianChen1129  @JerryZhou54 @SolitaryThinker

[misc] Polish V1 training code

---

fastvideo/v1/layers/activation.py
fastvideo/v1/layers/layernorm.py
fastvideo/v1/layers/mlp.py
fastvideo/v1/layers/rotary_embedding.py
fastvideo/v1/layers/visual_embedding.py

Reverts hao-ai-lab/FastVideo#432

Revert "Add torch.compile for all small ops"

---

.github/workflows/pr-test.yml

[CI] Restrict training CI to v1

---

fastvideo/v1/dataset/parquet_dataset_map_style.py
fastvideo/v1/pipelines/preprocess/preprocess_pipeline_i2v.py
fastvideo/v1/pipelines/preprocess/preprocess_pipeline_t2v.py
fastvideo/v1/pipelines/preprocess/v1_preprocess.py
scripts/preprocess/v1_preprocess_wan_data_i2v.sh
scripts/preprocess/v1_preprocess_wan_data_t2v.sh

1. fix sampler extra padding when drop_last=False
2. preprocessing breaks because of a our config reorg. fix that. https://github.com/hao-ai-lab/FastVideo/pull/505

[misc] Fix preprocessing and dataloader extra padding

---

fastvideo/v1/layers/layernorm.py

Formatting issue from https://github.com/hao-ai-lab/FastVideo/pull/577
cc @BrianChen1129 @SolitaryThinker 
Also now that buildkite is up, we should stop pushing to the public repo and run CIs for 3rd-party contributors.

[CI] Fix pre-commit CI

---

fastvideo/v1/fastvideo_args.py
fastvideo/v1/training/activation_checkpoint.py
fastvideo/v1/training/training_pipeline.py

[Feat] activation checkpointing

---

fastvideo/v1/layers/lora/linear.py

There was a problem in FSDP that silently disallows swapping DTensor.data.
cc @BrianChen1129 @SolitaryThinker

[LoRA] Fix lora merge weights

---

fastvideo/v1/training/training_pipeline.py

- Before, every validation would reinitialize with the same seed rather than continue generating from the seed set at initialization
After this PR:
- Always initialize seed only once for both training and validation using a separate `torch.generator`

[bugfix] [training] use separate generator for validation

---

.buildkite/pipeline.yml
fastvideo/v1/tests/modal/pr_test.py

Explicitly fetches pull request base so that PRs into branches other than main will work.

[CI] Fix CI for pull request targets other than main

---

.gitignore
examples/inference/lora/wan_lora_inference_from_ckpt.py
examples/training/finetune/wan_i2v_14b_480p/crush_smol/finetune_i2v.sh
examples/training/finetune/wan_i2v_14b_480p/crush_smol/finetune_i2v.slurm
examples/training/finetune/wan_i2v_14b_480p/crush_smol/finetune_i2v_lora.sh
examples/training/finetune/wan_t2v_1_3b/crush_smol/finetune_t2v.sh
examples/training/finetune/wan_t2v_1_3b/crush_smol/finetune_t2v.slurm
examples/training/finetune/wan_t2v_1_3b/crush_smol/finetune_t2v_lora.sh
fastvideo/v1/fastvideo_args.py
fastvideo/v1/layers/lora/linear.py
fastvideo/v1/pipelines/composed_pipeline_base.py
fastvideo/v1/pipelines/lora_pipeline.py
fastvideo/v1/tests/training/lora/l40s_reference_lora_wandb_summary.json
fastvideo/v1/tests/training/lora/test_lora_training.py
fastvideo/v1/training/checkpointing_utils.py
fastvideo/v1/training/training_pipeline.py
fastvideo/v1/training/training_utils.py

Previously Validation pipeline init mistakenly re-enabled grads for all params

[Bugfix] Fix LoRA trainable params and training ckpt loading

---

examples/training/finetune/wan_i2v_14B_480p/crush_smol/finetune_i2v.sh
examples/training/finetune/wan_t2v_1.3B/crush_smol/finetune_t2v.sh
examples/training/finetune/wan_t2v_1.3B/crush_smol/finetune_t2v_lora.sh

Someone changed the folder names

[Misc] Fix training scripts

---

csrc/attn/setup_vsa.py
csrc/attn/vsa/__init__.py
csrc/attn/vsa/block_sparse_wrapper.py

Compile the TK kernel whatever your device are.
Only call the TK kernel if you are on Hopper.
Probably do not need to run CI for this PR as I only modify the kernel code. 
I have make sure the kernel test past and the linting past.

[Misc] change installation logic of vsa

---

.github/workflows/vsa-publish.yml

specifies torch-cuda combinations, removes redundant builds

update version selection for VSA workflow

---

fastvideo/training/distillation_pipeline.py

- Remove redundant iterations
- Set noisy_input to pure noise when target_timestep_idx_int == 0

[bugfix] [dmd] Align backward simulation with dmd2 sample back

---

csrc/attn/tests/test_vsa.py
csrc/attn/vsa/block_sparse_h100.cu
fastvideo/pipelines/stages/denoising.py

1. fix seed.
2. remove unnecessary wait in vsa kernel
3. update vsa kernel test from abs max to relative max.

[Fix] fix seed in dmd denoising loop

---

examples/inference/lora/wan_lora_inference_from_ckpt.py
examples/training/finetune/wan_t2v_1.3B/crush_smol/finetune_t2v_lora.sh
fastvideo/entrypoints/video_generator.py
fastvideo/layers/lora/linear.py
fastvideo/pipelines/lora_pipeline.py
fastvideo/pipelines/stages/denoising.py
fastvideo/worker/executor.py
fastvideo/worker/gpu_worker.py
fastvideo/worker/multiproc_executor.py

Reduces video diff from validation. There's still some precision diff left to investigate 
(Left: validation. Right: inference)

Optionally use unmerged weights for inference

---

fastvideo/pipelines/stages/text_encoding.py
fastvideo/tests/stages/test_text_encoding.py

Improve the API of text encoding stage so that it can more easily be used as a standalone component.

[misc] Improve text encoding stage
